server:
  port: 8189
  servlet:
    context-path: /app
# http://localhost:8189/app

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app;MODE=PostgreSQL
    username: sa
    password:

  jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  h2:
      console:
        enabled: true
        settings:
          path: /h2-console
          trace: false
          web-allow-others: false

